version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdungeon-website
    container_name: jdungeon-website
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
