version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdungeon-website
    container_name: jdungeon-website
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    network_mode: "host"
